# Generated by Django 5.0.8 on 2024-10-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(null=True, verbose_name='Дата время'),
        ),
    ]
