# Generated by Django 5.0.8 on 2024-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_rename_name_task_title_alter_task_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
