# Generated by Django 5.0.8 on 2024-09-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_task_author_alter_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
